/**
 * Mock Telemetry & Security Intelligence Data
 * Provides realistic Android permissions catalogue, threat signatures, and accessible telemetry items.
 */

import { DetectionSignature, DeviceInfo, PermissionDetail, TelemetryTargetApp } from '../types/threat';

export const ANDROID_PERMISSIONS_CATALOG: Record<string, Omit<PermissionDetail, 'id' | 'isGranted'>> = {
  'android.permission.READ_SMS': {
    permissionName: 'android.permission.READ_SMS',
    riskLevel: 'HIGH',
    category: 'Messages & Communications',
    description: 'Allows an application to read SMS messages stored on the device or SIM card.',
    isDangerous: true,
    reason: 'Can expose sensitive 2FA codes, personal correspondence, and bank notifications.',
  },
  'android.permission.SEND_SMS': {
    permissionName: 'android.permission.SEND_SMS',
    riskLevel: 'HIGH',
    category: 'Messages & Communications',
    description: 'Allows an application to send SMS messages without user interaction.',
    isDangerous: true,
    reason: 'Can initiate premium-rate SMS toll fraud and transmit exfiltrated data.',
  },
  'android.permission.RECORD_AUDIO': {
    permissionName: 'android.permission.RECORD_AUDIO',
    riskLevel: 'HIGH',
    category: 'Microphone & Audio',
    description: 'Allows an application to record audio using the device microphone.',
    isDangerous: true,
    reason: 'Can covertly record ambient surroundings and telephone conversations.',
  },
  'android.permission.CAMERA': {
    permissionName: 'android.permission.CAMERA',
    riskLevel: 'HIGH',
    category: 'Camera & Vision',
    description: 'Required to be able to access the camera device.',
    isDangerous: true,
    reason: 'Can capture photos or video footage without conspicuous user prompts.',
  },
  'android.permission.BIND_ACCESSIBILITY_SERVICE': {
    permissionName: 'android.permission.BIND_ACCESSIBILITY_SERVICE',
    riskLevel: 'CRITICAL',
    category: 'System Accessibility & Overlays',
    description: 'Must be required by an AccessibilityService to ensure only the system can bind to it.',
    isDangerous: true,
    reason: 'Grants deep OS automation, keystroke logging, overlay injection, and permission self-granting.',
  },
  'android.permission.SYSTEM_ALERT_WINDOW': {
    permissionName: 'android.permission.SYSTEM_ALERT_WINDOW',
    riskLevel: 'HIGH',
    category: 'Display & Window Management',
    description: 'Allows an app to create windows shown on top of all other applications.',
    isDangerous: true,
    reason: 'Can construct deceptive phishing overlays over legitimate banking or password dialogs.',
  },
  'android.permission.REQUEST_INSTALL_PACKAGES': {
    permissionName: 'android.permission.REQUEST_INSTALL_PACKAGES',
    riskLevel: 'HIGH',
    category: 'Package & App Management',
    description: 'Allows an application to request installing packages.',
    isDangerous: true,
    reason: 'Can download and stage secondary malicious payload APKs (dropper behavior).',
  },
  'android.permission.ACCESS_FINE_LOCATION': {
    permissionName: 'android.permission.ACCESS_FINE_LOCATION',
    riskLevel: 'MEDIUM',
    category: 'Location & Tracking',
    description: 'Allows an app to access precise location from GPS, Wi-Fi, and cellular networks.',
    isDangerous: true,
    reason: 'Can log real-time physical coordinates and movement history.',
  },
  'android.permission.READ_CONTACTS': {
    permissionName: 'android.permission.READ_CONTACTS',
    riskLevel: 'MEDIUM',
    category: 'Personal Information',
    description: 'Allows an application to read the user contacts data.',
    isDangerous: true,
    reason: 'Can exfiltrate address books and social graph relations.',
  },
  'android.permission.READ_EXTERNAL_STORAGE': {
    permissionName: 'android.permission.READ_EXTERNAL_STORAGE',
    riskLevel: 'MEDIUM',
    category: 'Storage & Media',
    description: 'Allows an application to read from external storage.',
    isDangerous: true,
    reason: 'Can inspect user photos, documents, and cached application files.',
  },
  'android.permission.INTERNET': {
    permissionName: 'android.permission.INTERNET',
    riskLevel: 'LOW',
    category: 'Network & Connectivity',
    description: 'Allows applications to open network sockets.',
    isDangerous: false,
    reason: 'Standard network connectivity permission for internet access.',
  },
  'android.permission.ACCESS_NETWORK_STATE': {
    permissionName: 'android.permission.ACCESS_NETWORK_STATE',
    riskLevel: 'LOW',
    category: 'Network & Connectivity',
    description: 'Allows applications to access information about networks.',
    isDangerous: false,
    reason: 'Standard connectivity telemetry query.',
  },
};

export const DEFAULT_SIGNATURES: DetectionSignature[] = [
  {
    id: 'sig-001',
    code: 'SIG-ANDROID-00127',
    name: 'Stealth Banking Overlay & SMS Interceptor',
    threatType: 'Trojan',
    severity: 'HIGH',
    confidenceWeight: 40,
    description: 'Matches known banking trojan heuristic combining accessibility bindings with SMS exfiltration and overlay permissions.',
    ruleCriteria: 'READ_SMS + RECORD_AUDIO + BIND_ACCESSIBILITY_SERVICE',
    forbiddenPermissionCombos: [
      ['android.permission.READ_SMS', 'android.permission.RECORD_AUDIO', 'android.permission.BIND_ACCESSIBILITY_SERVICE'],
      ['android.permission.READ_SMS', 'android.permission.SYSTEM_ALERT_WINDOW', 'android.permission.BIND_ACCESSIBILITY_SERVICE'],
    ],
    isActive: true,
    createdAt: '2026-09-15T08:00:00Z',
  },
  {
    id: 'sig-002',
    code: 'SIG-ANDROID-00284',
    name: 'Known Malicious APK Hash Signature',
    threatType: 'Malware',
    severity: 'CRITICAL',
    confidenceWeight: 45,
    description: 'Exact SHA-256 hash match against threat intelligence repository of confirmed spyware droppers.',
    ruleCriteria: 'SHA-256 Hash Match',
    knownMaliciousHashes: [
      '7c4a8d09ca3762af61e59520943dc2644265bb6d07e60d9d863f683bc430e321',
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      'a94a8fe5ccb19ba61c4c0873d391e987982fbbd342080a221f7c8976b008d591',
    ],
    isActive: true,
    createdAt: '2026-09-20T12:00:00Z',
  },
  {
    id: 'sig-003',
    code: 'SIG-ANDROID-00319',
    name: 'Deceptive Capability Flashlight/Utility Pattern',
    threatType: 'Potentially Unwanted Application',
    severity: 'HIGH',
    confidenceWeight: 35,
    description: 'Utility application requesting sensitive background audio, location, and storage disproportionate to stated utility scope.',
    ruleCriteria: 'RECORD_AUDIO + ACCESS_FINE_LOCATION in Utility/Tools category',
    forbiddenPermissionCombos: [
      ['android.permission.RECORD_AUDIO', 'android.permission.ACCESS_FINE_LOCATION', 'android.permission.READ_CONTACTS'],
      ['android.permission.RECORD_AUDIO', 'android.permission.READ_SMS'],
    ],
    isActive: true,
    createdAt: '2026-09-22T14:30:00Z',
  },
  {
    id: 'sig-004',
    code: 'SIG-ANDROID-00491',
    name: 'Aggressive Adware & Background Dropper',
    threatType: 'Adware',
    severity: 'MEDIUM',
    confidenceWeight: 30,
    description: 'Application requests package installer capability alongside system alert window and communicates with aggressive ad networks.',
    ruleCriteria: 'REQUEST_INSTALL_PACKAGES + SYSTEM_ALERT_WINDOW',
    forbiddenPermissionCombos: [
      ['android.permission.REQUEST_INSTALL_PACKAGES', 'android.permission.SYSTEM_ALERT_WINDOW'],
    ],
    isActive: true,
    createdAt: '2026-09-28T09:15:00Z',
  },
  {
    id: 'sig-005',
    code: 'SIG-ANDROID-00512',
    name: 'Anomalous C2 Communication Infrastructure',
    threatType: 'Suspicious Behavior',
    severity: 'MEDIUM',
    confidenceWeight: 35,
    description: 'Telemetry logs show outbound socket connections to unrated dynamic DNS domains or known malicious IP blocks without package correlation.',
    ruleCriteria: 'External C2 connection over non-standard port or unrated dynamic domain',
    flaggedDomains: [
      'c2-telemetry-relay-node.xyz',
      'stealth-update-srv8.top',
      'auth-verify-portal-redirect.online',
      'data-exfil-staging.cc',
    ],
    isActive: true,
    createdAt: '2026-09-30T16:00:00Z',
  },
];

export const INITIAL_TELEMETRY_APPS: TelemetryTargetApp[] = [
  {
    id: 'app-01',
    name: 'Quick Flashlight HD Pro',
    packageName: 'com.superflash.brightlight',
    version: '2.4.1',
    iconBg: 'bg-amber-500',
    category: 'Utility & Tools',
    requestedPermissions: [
      'android.permission.CAMERA',
      'android.permission.RECORD_AUDIO',
      'android.permission.READ_SMS',
      'android.permission.INTERNET',
      'android.permission.ACCESS_NETWORK_STATE',
    ],
    signatureMatch: 'SIG-ANDROID-00319',
    fileName: 'quick_flashlight_pro_v2.apk',
    fileSizeBytes: 14200000,
    fileHash: '5a2f8c09ca3762af61e59520943dc2644265bb6d07e60d9d863f683bc4309999',
    networkEndpoints: ['analytics-traffic.xyz', 'api.superflash.com'],
    behaviorFlags: ['Requested microphone access on simple flashlight app', 'Background service running continuously'],
    isSystemApp: false,
    installedAt: '2026-09-25T11:20:00Z',
  },
  {
    id: 'app-02',
    name: 'Secure Token Authenticator',
    packageName: 'com.banksecurity.authlogin',
    version: '1.0.8',
    iconBg: 'bg-red-500',
    category: 'Finance / Security',
    requestedPermissions: [
      'android.permission.READ_SMS',
      'android.permission.RECORD_AUDIO',
      'android.permission.BIND_ACCESSIBILITY_SERVICE',
      'android.permission.SYSTEM_ALERT_WINDOW',
      'android.permission.INTERNET',
      'android.permission.READ_CONTACTS',
    ],
    signatureMatch: 'SIG-ANDROID-00127',
    fileName: 'bank_auth_patch.apk',
    fileSizeBytes: 8900000,
    fileHash: '7c4a8d09ca3762af61e59520943dc2644265bb6d07e60d9d863f683bc430e321',
    networkEndpoints: ['auth-verify-portal-redirect.online', 'c2-telemetry-relay-node.xyz'],
    behaviorFlags: [
      'Deceptive overlay window generated on top of banking app',
      'Accessibility service read user screen contents',
      'SMS interceptor active',
    ],
    isSystemApp: false,
    installedAt: '2026-10-01T23:45:00Z',
  },
  {
    id: 'app-03',
    name: 'File Manager & Media Booster',
    packageName: 'com.boostmedia.cleanfiles',
    version: '4.2.0',
    iconBg: 'bg-indigo-500',
    category: 'Productivity',
    requestedPermissions: [
      'android.permission.REQUEST_INSTALL_PACKAGES',
      'android.permission.SYSTEM_ALERT_WINDOW',
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.INTERNET',
    ],
    signatureMatch: 'SIG-ANDROID-00491',
    fileName: 'file_booster_v4.apk',
    fileSizeBytes: 22100000,
    fileHash: '11a48fe5ccb19ba61c4c0873d391e987982fbbd342080a221f7c8976b008d591',
    networkEndpoints: ['ad-delivery-network.top', 'stealth-update-srv8.top'],
    behaviorFlags: ['Initiated background download of third-party APK without user confirmation'],
    isSystemApp: false,
    installedAt: '2026-09-18T14:10:00Z',
  },
  {
    id: 'app-04',
    name: 'Signal Private Messenger',
    packageName: 'org.thoughtcrime.securesms',
    version: '7.12.0',
    iconBg: 'bg-blue-600',
    category: 'Communication',
    requestedPermissions: [
      'android.permission.INTERNET',
      'android.permission.CAMERA',
      'android.permission.RECORD_AUDIO',
      'android.permission.READ_CONTACTS',
      'android.permission.ACCESS_NETWORK_STATE',
    ],
    fileSizeBytes: 45000000,
    fileHash: '99bf8c09ca3762af61e59520943dc2644265bb6d07e60d9d863f683bc4301111',
    isSystemApp: false,
    installedAt: '2026-08-10T09:00:00Z',
  },
  {
    id: 'app-05',
    name: 'Google Maps Navigation',
    packageName: 'com.google.android.apps.maps',
    version: '11.140.0',
    iconBg: 'bg-emerald-600',
    category: 'Travel & Navigation',
    requestedPermissions: [
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.INTERNET',
      'android.permission.ACCESS_NETWORK_STATE',
    ],
    fileSizeBytes: 82000000,
    fileHash: '333a8d09ca3762af61e59520943dc2644265bb6d07e60d9d863f683bc4303333',
    isSystemApp: true,
    installedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'app-06',
    name: 'WhatsApp Messenger',
    packageName: 'com.whatsapp',
    version: '2.26.18',
    iconBg: 'bg-emerald-500',
    category: 'Communication',
    requestedPermissions: [
      'android.permission.CAMERA',
      'android.permission.RECORD_AUDIO',
      'android.permission.READ_CONTACTS',
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.INTERNET',
    ],
    fileSizeBytes: 68000000,
    fileHash: '888a8d09ca3762af61e59520943dc2644265bb6d07e60d9d863f683bc4308888',
    isSystemApp: false,
    installedAt: '2026-07-14T15:30:00Z',
  },
];

export const INITIAL_DEVICE_INFO: DeviceInfo = {
  id: 'dev-pixel9-001',
  deviceName: 'Google Pixel 9 Pro',
  platform: 'Android',
  platformVersion: 'Android 15 (API 35)',
  appVersion: 'ThreatGuard Scanner v1.0.4',
  securityPatchLevel: '2026-09-05',
  isRooted: false,
  playProtectStatus: 'Active',
  lastScanAt: '2026-10-01T15:45:00Z',
  overallStatus: 'ACTION_REQUIRED',
};
